# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: プログラミング・シンポジウム
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "/test" # the subpath of your site, e.g. /blog
url: "https://www.prosym.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: embulk

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - .ruby-version
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

collections:
  posts:
    output: true
    permalink: /articles/:year/:month/:day/:title:output_ext

feed:
  collections:
    posts:
      path: "/articles/feed.xml"
